# Problem 29

# How many distinct terms are in the sequence generated by a^(b) for
# 2 <= a <= 100 and 2 <= b <= 100?

seq = []
for a in range(2, 101):
    for b in range(2, 101):
        num = a**b
        if num not in seq:
            seq.append(num)
print(len(seq))